name = "Add to ticktick"
description = "Add the selected text to ticktick/dida365"
author = "C Shen"
version = "1.0"
icon = "ticktick.png"
actions = "execute_shell_script"
shell_script = "script.sh {POPUP_PLAIN_TEXT}"
