    name = "Deepseek"
    description = "Query Deepseek"
    author = "C Shen"
    version = "1.0"
    icon = "artificial-intelligence.png"
    actions = "execute_shell_script"
    shell_script = "script.sh {POPUP_PLAIN_TEXT}"
